version: '3'
services:

  database:
    image: simot18/takehomedb
    networks: 
      - backendNetwork
  
  backend:
    image: simot18/takehomebackend
    depends_on:
      - database
    ports:
      - 5000:5000
    networks: 
      - frontendNetwork
      - backendNetwork

  proxy:
    image: simot18/takehomeproxy
    ports:
      - 443:80
      - 80:80
    depends_on: 
      - backend
    networks:
      - frontendNetwork

networks:
  backendNetwork:
    driver: bridge
  frontendNetwork:
    driver: bridge